export const nigeriaStates: Record<string, string[]> = {
  "Abia": ["Aba", "Arochukwu", "Bende", "Ohafia", "Umuahia"],
  "Abuja (FCT)": ["Abaji", "Abuja Municipal", "Bwari", "Gwagwalada", "Kuje", "Kwali"],
  "Adamawa": ["Demsa", "Jimeta", "Mubi", "Numan", "Yola"],
  "Akwa Ibom": ["Girei", "Mubi", "Numan", "Yola"],
  "Anambra": ["Eket", "Ikot Ekpene", "Oron", "Uyo"],
  "Bauchi": ["Jimeta", "Mubi", "Numan", "Yola"],
  "Bayelsa": ["Eket", "Ikot Ekpene", "Oron", "Uyo"],
  "Benue": ["Bauchi", "Azare", "Misau", "Jama'are"],
  "Borno": ["Bauchi", "Azare", "Misau", "Jama'are"],
  "Cross River": ["Brass", "Ogbia", "Sagbama", "Yenagoa"],
  "Delta": ["Brass", "Ogbia", "Sagbama", "Yenagoa"],
  "Ebonyi": ["Gboko", "Katsina-Ala", "Makurdi", "Oturkpo"],
  "Edo": ["Asaba", "Sapele", "Ughelli", "Warri", "Effurun"],
  "Ekiti": ["Abakaliki", "Afikpo", "Onueke"],
  "Enugu": ["Enugu", "Nsukka", "Oji River", "Awgu"],
  "Gombe": ["Gombe", "Kaltungo", "Nafada"],
  "Imo": ["Awka", "Onitsha", "Nnewi", "Ekwulobia"],
  "Jigawa": ["Dutse", "Hadejia", "Kazaure", "Gumel"],
  "Kaduna": ["Biu", "Dikwa", "Maiduguri"],
  "Kano": ["Kaduna", "Kafanchan", "Zaria"],
  "Katsina": ["Daura", "Funtua", "Katsina"],
  "Kebbi": ["Daura", "Funtua", "Katsina"],
  "Kogi": ["Idah", "Kabba", "Lokoja", "Okene"],
  "Kwara": ["Idah", "Kabba", "Lokoja", "Okene"],
  "Lagos": ["Agege", "Epe", "Ikeja", "Ikorodu", "Lagos Island", "Surulere", "Yaba"],
  "Nasarawa": ["Gombe", "Kaltungo", "Nafada"],
  "Niger": ["Akwanga", "Keffi", "Lafia"],
  "Ogun": ["Ilorin", "Jebba", "Lafiagi", "Offa"],
  "Ondo": ["Abeokuta", "Ijebu-Ode", "Ilaro", "Shagamu"],
  "Osun": ["Akure", "Ikare", "Oka", "Ondo", "Owo"],
  "Oyo": ["Eruwa", "Ibadan", "Iseyin", "Ogbomosho", "Oyo", "Saki"],
  "Plateau": ["Bida", "Kontagora", "Lapai", "Minna", "Suleja"],
  "Rivers": ["Calabar", "Ikom", "Obudu", "Ogoja", "Ugep"],
  "Sokoto": ["Argungu", "Birnin Kebbi", "Gwandu", "Yelwa"],
  "Taraba": ["Bida", "Kontagora", "Lapai", "Minna", "Suleja"],
  "Yobe": ["Biu", "Dikwa", "Maiduguri"],
  "Zamfara": ["Gusau", "Kauran Namoda"]
};
